apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: syncup
type: Opaque
data:
  AUTH_SECRET: S25NWHlkeDdrZUEzdFQ4eVB0QWJVd0dlRVlSQ0VBNE9PdnhrbS9CSWtTRT0=
  AUTH_GOOGLE_ID: MTM3MTU5MjkwMjc5LTBub2o2ZTl1a2M3OWJqcmpobzBwdWRjdHA1Z2dpODI0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  AUTH_GOOGLE_SECRET: R09DU1BYLVhqd2VpQmtiNG9OMnhtaXpkSnQ1aVc1RHIwZ3U=
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVFPeGE3SlpRdGNmR0FacVdGN2wwQm00cmg3VGdiWmhYWDNiUzVzMkR6cGFkRGlEUDF0N3d5Q0g4endlTDc5TnNOMEdkWW1Za2E2MEtucDA0QWFHbmpSNzAwOFBzREdxZmc=
  NEXT_PUBLIC_S3_URL: aHR0cHM6Ly9zeW5jdXBjbG91ZC5zMy5ldS1ub3J0aC0xLmFtYXpvbmF3cy5jb20=
  NEXT_PUBLIC_BASIC_URL: aHR0cDovL3N5bmN1cC5taGRhamZlci5pbg==
  JWT_AUTHSECRET: c2VjcmV0LWtleQ==
  REFRESH_SECRET: c2VjcmV0LWtleTAx
  PORT: MzAwMA==
  AWS_ACCESS_KEY: QUtJQTJVQzNBSkRCNFIyMlpaRTM=
  AWS_SECRET_ACCESS_KEY: aHU4eWZmOWhQQ1RDbDkwZkQwTG9QbVl1bmdJV2o0SUtMa2lRaVFaxA==
  AWS_S3_REGION: ZXUtbm9ydGgtMQ==
  AWS_S3_BUCKET_NAME: c3luY3VwY2xvdWQ=
  STRIPE_SECRET_KEY: c2tfdGVzdF81UVE=
  DB_URL: bW9uZ29kYitzcnY6Ly9hamZlcmFqdTk5NjE6QWNodWFqdTZAY2x1c3Rlci5wM2lkdW1qLm1vbmdvZGIubmV0L3N5bmNVcC11c2VyLXNlcnZpY2U=
