apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: syncup
type: Opaque
data:
  NEXTAUTH_SECRET: S25NWHlkeDdrZUEzdFQ4eVB0QWJVd0dlRVlSQ0VBNE9PdnhrbS9CSWtTRT0=
  GOOGLE_CLIENT_ID: MTM3MTU5MjkwMjc5LTBub2o2ZTl1a2M3OWJqcmpobzBwdWRjdHA1Z2dpODI0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLVhqd2VpQmtiNG9OMnhtaXpkSnQ1aVc1RHIwZ3U=
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVFPeGE3SlpRdGNmR0FacVdGN2wwQm00cmg3VGdiWmhYWDNiUzVzMkR6cGFkRGlEUDF0N3d5Q0g4endlTDc5TnNOMEdkWW1Za2E2MEtucDA0QWFHbmpSNzAwOFBzREdxZmc=
  NEXT_PUBLIC_S3_URL: aHR0cHM6Ly9zeW5jdXBidWNrZXQuczMuZXUtbm9ydGgtMS5hbWF6b25hd3MuY29t
  NEXT_PUBLIC_BASIC_URL: aHR0cHM6Ly9zeW5jdXAubWhkYWpmZXIuaW4v
  NEXTAUTH_URL: aHR0cHM6Ly9zeW5jdXAubWhkYWpmZXIuaW4v

  JWT_AUTHSECRET: c2VjcmV0LWtleQ==
  REFRESH_SECRET: c2VjcmV0LWtleTAx
  PORT: MzAwMA==
  AWS_ACCESS_KEY: QUtJQVFYVUlZQUdSWE1ZU1lLTk0=
  AWS_SECRET_ACCESS_KEY: cjVEK29VTTJwbnl2WUg5MUJEUXhYWFViS2k2VzQxUXdzTnBRT1pyZA==
  AWS_S3_REGION: ZXUtbm9ydGgtMQ==
  AWS_S3_BUCKET_NAME: c3luY3VwYnVja2V0
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVFPeGE3SlpRdGNmR0FacVJjeWdJaEJTTmdQQkhrTjJsZGs5NE02OWt3NFRzUklGNFBHTkM5YmdDVnlDSlk5R0t3MkZJbVp0TjJpbmY0RnpCWXRHT2I5RTAwTkVQUXBiZk4=
<<<<<<< Updated upstream
=======
  NODEMAILER_PASSWORD: em9ieW54aGFqd3VyYnh3cQ==
  NODEMAILER_EMAIL: YWpmZXJhanU5OTYxQGdtYWlsLmNvbQ==
>>>>>>> Stashed changes
